/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "tertiary": "#384d43",
        "secondary-fixed-dim": "#a5d0b9",
        "surface-variant": "#dfe4df",
        "background": "#f6fbf5",
        "tertiary-fixed-dim": "#b4ccbe",
        "tertiary-container": "#4f655a",
        "surface-container-low": "#f0f5f0",
        "primary-container": "#2f6b4f",
        "primary": "#125238",
        "secondary": "#3f6653",
        "on-error": "#ffffff",
        "on-background": "#181d1a",
        "on-tertiary-fixed": "#0b1f17",
        "on-secondary": "#ffffff",
        "surface-container": "#ebefea",
        "surface-bright": "#f6fbf5",
        "surface-container-highest": "#dfe4df",
        "on-primary-fixed": "#002113",
        "on-secondary-fixed": "#002114",
        "primary-fixed-dim": "#96d4b2",
        "outline": "#707972",
        "on-surface": "#181d1a",
        "surface-tint": "#2d694d",
        "on-secondary-fixed-variant": "#274e3d",
        "surface-container-high": "#e5e9e4",
        "secondary-container": "#beead1",
        "on-primary-fixed-variant": "#105137",
        "on-primary-container": "#aae9c6",
        "error-container": "#ffdad6",
        "on-secondary-container": "#436b58",
        "error": "#ba1a1a",
        "on-surface-variant": "#404943",
        "inverse-surface": "#2c322e",
        "on-tertiary-container": "#c9e1d3",
        "inverse-on-surface": "#edf2ed",
        "on-primary": "#ffffff",
        "inverse-primary": "#96d4b2",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#364b41",
        "secondary-fixed": "#c1ecd4",
        "primary-fixed": "#b1f0cd",
        "outline-variant": "#c0c9c1",
        "on-error-container": "#93000a",
        "surface": "#f6fbf5",
        "tertiary-fixed": "#d0e8da",
        "surface-dim": "#d7dbd6",

        "canvas-ground": "#F4F4F0",
        "sheet-surface": "#FAFAF8",
        "ink-heavy": "#1F2421",
        "ink-body": "#2D312E",
        "ink-subdued": "#636B66",
        "accent-primary": "#2F6B4F",
        "accent-deep": "#1B4332",
        "accent-muted-tint": "#CBE3D5",
        "accent-pale-wash": "#E3EFE8",
        "accent-faint-wash": "#F0F6F2",

        "risk-low-text": "#2E7D32",
        "risk-low-surface": "#E8F5E9",
        "risk-low-outline": "#C8E6C9",
        "risk-medium-text": "#D97706",
        "risk-medium-surface": "#FEF3C7",
        "risk-medium-outline": "#FDE68A",
        "risk-high-text": "#DC2626",
        "risk-high-surface": "#FEE2E2",
        "risk-high-outline": "#FECACA"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "gutter-lg": "2rem",
        "gutter": "1.5rem",
        "gutter-sm": "1rem",
        "margin": "2rem",
        "margin-desktop": "3rem",
        "margin-mobile": "1rem",
        "space-xl": "2.5rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display": ["52px", { "lineHeight": "60px", "letterSpacing": "-0.03em", "fontWeight": "600" }],
        "headline-lg": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.025em", "fontWeight": "600" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "headline-sm": ["18px", { "lineHeight": "26px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "26px", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "22px", "letterSpacing": "0em", "fontWeight": "400" }],
        "body-sm": ["12px", { "lineHeight": "18px", "letterSpacing": "0.005em", "fontWeight": "400" }],
        "legal-contract": ["13px", { "lineHeight": "22px", "letterSpacing": "0.005em", "fontWeight": "400" }],
        "label-md": ["13px", { "lineHeight": "18px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.04em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
