

export default function TermsOfService() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-20 text-ink-body">
      <h1 className="text-headline-lg text-ink-heavy mb-8">Terms of Service</h1>
      <p className="text-body-md text-ink-subdued mb-10">Effective Date: [Effective Date]</p>

      <div className="bg-surface-container-low rounded-xl p-6 mb-12">
        <h2 className="text-headline-sm text-ink-heavy mb-4">Table of contents</h2>
        <ul className="space-y-2 text-body-md">
          <li><a href="#acceptance" className="text-accent-primary hover:underline">1. Acceptance of terms</a></li>
          <li><a href="#what-redline-is" className="text-accent-primary hover:underline">2. What Redline is (and isn't)</a></li>
          <li><a href="#eligibility" className="text-accent-primary hover:underline">3. Eligibility and accounts</a></li>
          <li><a href="#free-beta" className="text-accent-primary hover:underline">4. Free beta access</a></li>
          <li><a href="#responsibilities" className="text-accent-primary hover:underline">5. Your responsibilities</a></li>
          <li><a href="#ai-output" className="text-accent-primary hover:underline">6. AI output — no legal advice, no attorney-client relationship</a></li>
          <li><a href="#content-ip" className="text-accent-primary hover:underline">7. Your content and intellectual property</a></li>
          <li><a href="#data-security" className="text-accent-primary hover:underline">8. Data, confidentiality, and security</a></li>
          <li><a href="#prohibited-uses" className="text-accent-primary hover:underline">9. Prohibited uses</a></li>
          <li><a href="#disclaimers" className="text-accent-primary hover:underline">10. Disclaimers and limitation of liability</a></li>
          <li><a href="#indemnification" className="text-accent-primary hover:underline">11. Indemnification</a></li>
          <li><a href="#termination" className="text-accent-primary hover:underline">12. Termination</a></li>
          <li><a href="#changes" className="text-accent-primary hover:underline">13. Changes to these terms</a></li>
          <li><a href="#governing-law" className="text-accent-primary hover:underline">14. Governing law</a></li>
          <li><a href="#contact" className="text-accent-primary hover:underline">15. Contact</a></li>
        </ul>
      </div>

      <div className="space-y-10 text-body-lg">
        <section id="acceptance">
          <h2 className="text-headline-md text-ink-heavy mb-4">1. Acceptance of terms</h2>
          <p>By creating an account or using Redline ("Redline," "we," "us," or "our"), you agree to these Terms of Service ("Terms"). If you do not agree, do not use the service. If you are using Redline on behalf of an organization, you represent that you have authority to bind that organization to these Terms.</p>
        </section>

        <section id="what-redline-is">
          <h2 className="text-headline-md text-ink-heavy mb-4">2. What Redline is (and isn't)</h2>
          <p className="mb-4">Redline is an AI-powered contract intelligence platform that analyzes, redlines, and helps negotiate contracts for freelancers, independent consultants, and small businesses. Redline uses automated, machine-generated analysis — including risk scoring, clause suggestions, and draft counter-proposal language — to help you understand and negotiate agreements faster.</p>
          <p>Redline is not a law firm and does not provide legal advice. Using Redline does not create an attorney-client relationship between you and Redline, its owners, or its personnel. Redline's output is generated by an AI system based on general commercial patterns and precedent data; it is not a substitute for review by a licensed attorney, particularly for high-value, high-risk, or jurisdiction-sensitive agreements. You are solely responsible for any decision to accept, reject, sign, or act on any contract, clause, or suggestion Redline provides.</p>
        </section>

        <section id="eligibility">
          <h2 className="text-headline-md text-ink-heavy mb-4">3. Eligibility and accounts</h2>
          <p>You must be at least 18 years old (or the age of majority in your jurisdiction) and able to form a binding contract to use Redline. You're responsible for maintaining the confidentiality of your account credentials and for all activity under your account. Notify us promptly at arunbalajithangavel66@gmail.com if you suspect unauthorized use of your account.</p>
        </section>

        <section id="free-beta">
          <h2 className="text-headline-md text-ink-heavy mb-4">4. Free beta access</h2>
          <p>Redline is currently offered free of charge during its beta period. Features, limits, and pricing may change as the product develops. If we introduce paid plans in the future, we will provide reasonable advance notice before any charges apply to your account, and continued use of paid features after that notice constitutes acceptance of the applicable pricing.</p>
        </section>

        <section id="responsibilities">
          <h2 className="text-headline-md text-ink-heavy mb-4">5. Your responsibilities</h2>
          <p className="mb-2">You agree to:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Only upload documents you have the legal right to upload and share (your own contracts, or those you're authorized to review on behalf of a client or employer)</li>
            <li>Use Redline for lawful purposes only, and not to draft, redline, or negotiate contracts intended to defraud, mislead, or unlawfully disadvantage another party</li>
            <li>Independently verify any clause, redline, risk score, or counter-proposal before relying on it in a real negotiation or signing a document</li>
            <li>Keep your account information accurate and up to date</li>
          </ul>
        </section>

        <section id="ai-output">
          <h2 className="text-headline-md text-ink-heavy mb-4">6. AI output — no legal advice, no attorney-client relationship</h2>
          <p>All risk scores, clause suggestions, plain-language explanations, counter-proposal drafts, and "market benchmark" statistics generated by Redline are produced algorithmically and may be incomplete, generic, or incorrect for your specific situation, jurisdiction, or counterparty. Redline does not warrant that any suggested clause is enforceable, compliant with applicable law, or appropriate for your circumstances. For contracts involving significant financial, legal, or regulatory exposure, consult a licensed attorney in the relevant jurisdiction before signing.</p>
        </section>

        <section id="content-ip">
          <h2 className="text-headline-md text-ink-heavy mb-4">7. Your content and intellectual property</h2>
          <p className="mb-4">You retain all ownership rights to the contracts, clauses, and other documents you upload to Redline ("Your Content"). By uploading Your Content, you grant Redline a limited, non-exclusive, worldwide license to process, analyze, and store Your Content solely to provide and improve the service to you, consistent with our Privacy Policy. We do not claim ownership of Your Content, and — as described in our Privacy Policy — we do not use Your Content to train shared or third-party AI models.</p>
          <p>Redline's own software, design, branding, risk-scoring methodology, and generated UI/analysis templates remain the property of [Company Legal Name].</p>
        </section>

        <section id="data-security">
          <h2 className="text-headline-md text-ink-heavy mb-4">8. Data, confidentiality, and security</h2>
          <p>We take reasonable technical and organizational measures to protect Your Content, including encryption in transit and at rest. Full detail is in our <a href="/privacy" className="text-accent-primary hover:underline">Privacy Policy</a>. No system is 100% secure, and you acknowledge that Redline cannot guarantee absolute security of data transmitted or stored.</p>
        </section>

        <section id="prohibited-uses">
          <h2 className="text-headline-md text-ink-heavy mb-4">9. Prohibited uses</h2>
          <p className="mb-2">You may not use Redline to:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Upload malicious files, attempt to reverse-engineer or scrape the service, or interfere with its normal operation</li>
            <li>Impersonate any person or entity, or misrepresent your affiliation with a person or entity</li>
            <li>Use generated counter-proposals or redlines to knowingly mislead a counterparty about material facts</li>
            <li>Violate any applicable law or the intellectual property, privacy, or other rights of any third party</li>
          </ul>
        </section>

        <section id="disclaimers">
          <h2 className="text-headline-md text-ink-heavy mb-4">10. Disclaimers and limitation of liability</h2>
          <p>Redline is provided "as is" and "as available," without warranties of any kind, express or implied, including implied warranties of merchantability, fitness for a particular purpose, and non-infringement. To the maximum extent permitted by law, Redline and its officers, employees, and affiliates will not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits, revenue, or business opportunity, arising from your use of — or reliance on — the service, even if advised of the possibility of such damages. Our total liability for any claim arising from these Terms or the service is limited to the amount you paid Redline in the twelve (12) months preceding the claim, or $100, whichever is greater (or, during the free beta period, limited to $100).</p>
        </section>

        <section id="indemnification">
          <h2 className="text-headline-md text-ink-heavy mb-4">11. Indemnification</h2>
          <p>You agree to indemnify and hold Redline harmless from any claims, damages, liabilities, and expenses (including reasonable attorneys' fees) arising from your use of the service, Your Content, or your violation of these Terms.</p>
        </section>

        <section id="termination">
          <h2 className="text-headline-md text-ink-heavy mb-4">12. Termination</h2>
          <p>You may stop using Redline and delete your account at any time. We may suspend or terminate your access if you violate these Terms or if we reasonably believe your use poses a risk to Redline or other users. Upon termination, your right to use the service ends immediately; provisions of these Terms that by their nature should survive (including Sections 6, 7, 8, 10, and 11) will survive.</p>
        </section>

        <section id="changes">
          <h2 className="text-headline-md text-ink-heavy mb-4">13. Changes to these terms</h2>
          <p>We may update these Terms from time to time. We'll post the updated version with a new effective date, and for material changes we'll make reasonable efforts to notify you (e.g. by email or in-app notice). Continued use of Redline after changes take effect constitutes acceptance of the revised Terms.</p>
        </section>

        <section id="governing-law">
          <h2 className="text-headline-md text-ink-heavy mb-4">14. Governing law</h2>
          <p>These Terms are governed by the laws of [Jurisdiction/Governing Law], without regard to its conflict-of-laws principles.</p>
        </section>

        <section id="contact">
          <h2 className="text-headline-md text-ink-heavy mb-4">15. Contact</h2>
          <p>Questions about these Terms: <a href="mailto:arunbalajithangavel66@gmail.com" className="text-accent-primary hover:underline">arunbalajithangavel66@gmail.com</a></p>
        </section>
      </div>
    </div>
  );
}
